### PR TITLE
Changed title from 'Minimum Movement Catalog' to 'Minimum Movement'

### PR DESCRIPTION
**Pull request by Jwright707**
Related to issue #1

### CODE REVIEW

**Comment by katychuang** [comment]
Great work. Just 1 more change in `src/pages/home.js` file, the title on Line 271 should also be changed. I will merge after that is is modified.

**Comment by Jwright707** [comment]
Hi @katychuang , thank you for the feedback! Just pushed the requested change 👍

**Comment by katychuang** [comment]
Good work :+1: 

Just need it to be Minim**um** instead of Minimal to match user requirements

**Comment by Jwright707** [comment]
Just pushed the fix on the spelling. My bad, I completely overlooked that 👍

**Pull request merged**
